version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - PRODUCTION_PG_USER=${PRODUCTION_PG_USER}
      - PRODUCTION_PG_PASSWORD=${PRODUCTION_PG_PASSWORD}
      - PRODUCTION_PG_DATABASE=${PRODUCTION_PG_DATABASE}
      - PRODUCTION_PG_HOST=db
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["npm", "run", "start"]  
  
  db:
    image: postgres:16 
    environment:
      POSTGRES_USER: ${PRODUCTION_PG_USER}
      POSTGRES_PASSWORD: ${PRODUCTION_PG_PASSWORD}
      POSTGRES_DB: ${PRODUCTION_PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:6543"
    restart: always

volumes:
  postgres_data:
